# Disable rules you don't want to enforce
disabled_rules:
  - line_length
  - trailing_whitespace

# Enable opt-in rules you specifically want
opt_in_rules:
  - force_unwrapping

# Specify which folders/files to include
included:
  - SampleCIApp
  - SampleCIAppTests

# Exclude folders/files from linting
excluded:
  - Pods
  - Carthage
  - fastlane

# Treat warnings as errors if needed (strict mode)
strict: false

# Output format for Xcode or CI
reporter: "xcode"
