# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "SampleCIApp",
      device: "iPhone 16", # simulator device
      clean: true
    )
  end

  desc "Build app without signing"
  lane :build do
    build_app(
      scheme: "SampleCIApp",
      export_method: "development",
      skip_codesigning: true
    )
  end

end

