name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 🔹 Make sure Xcode points to the right version
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Show Xcode version
      run: xcodebuild -version

    - name: List available simulators (debug step)
      run: xcrun simctl list devices

    # 🔹 Set up Ruby (required for Fastlane)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2   # GitHub macOS runners support this
        bundler-cache: true

    # 🔹 Install gems (Fastlane comes from your Gemfile)
    - name: Install dependencies
      run: bundle install

    # 🔹 Run tests via Fastlane
    - name: Run Fastlane tests
      run: bundle exec fastlane test

    # 🔹 Build app via Fastlane
    - name: Run Fastlane build
      run: bundle exec fastlane build

