name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Build app
        run: |
          DEST=$(xcrun simctl list devices available | grep -m 1 "iPhone" | awk -F '[()]' '{print $2}')
          echo "Using destination: $DEST"
          xcodebuild \
            -scheme SampleCIApp \
            -sdk iphonesimulator \
            -destination "id=$DEST" \
            clean build

      - name: Run tests
        run: |
          DEST=$(xcrun simctl list devices available | grep -m 1 "iPhone" | awk -F '[()]' '{print $2}')
          echo "Using destination: $DEST"
          xcodebuild \
            -scheme SampleCIApp \
            -sdk iphonesimulator \
            -destination "id=$DEST" \
            test

